version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-2
    IMAGE_REPO_NAME: gringotts
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ACCOUNT_ID=184244027379
      - REPOSITORY_URI=184244027379.dkr.ecr.ap-south-2.amazonaws.com/gringotts
      - aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin 184244027379.dkr.ecr.ap-south-2.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - docker build -t gringotts .
      - docker tag gringotts:latest 184244027379.dkr.ecr.ap-south-2.amazonaws.com/gringotts:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 184244027379.dkr.ecr.ap-south-2.amazonaws.com/gringotts:latest
      - echo Writing image definitions file...
      - printf '[{"name":"api-task","imageUri":"%s"}]' 184244027379.dkr.ecr.ap-south-2.amazonaws.com/gringotts:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
